import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "src/components/Layout";
import profilePic from "../../public/images/profile/profile.png";
import AnimatedText from "src/components/AnimatedText";
import { ExternalLink } from "src/components/Icons";
import Link from "next/link";
import HireMe from "src/components/HireMe";
import LightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark min-h-screen">
        <Layout className="pt-0">
          <div className=" flex items-center justify-betweens w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Ali Hamza"
                className="w-full h-auto"
              />
            </div>
            <div className=" flex flex-col w-[48%] gap-6 items-center self-center">
              <AnimatedText
                text={"Turning Vision Into Reality With Code And Design"}
                className={"!text-left"}
              />
              <p className="text-black ">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="w-full flex flex-row gap-3 text-lg justify-start items-center">
                <Link
                  href="/dummy.pdf"
                  target="_blank"
                  download={true}
                  className="border-2 flex flex-row justify-center items-center px-2 gap-2 w-40 h-[52px] font-bold text-light hover:bg-light hover:text-dark hover:border-black  bg-dark rounded-md"
                >
                  Resume
                  <ExternalLink className="w-8 h-8" />
                </Link>
                <a
                  href="mailto:itx.alihamza.pro@gmail.com"
                  rel="noopener noreferrer"
                  target="_blank"
                  className="underline"
                >
                  Content
                </a>
              </div>
            </div>
          </div>
        </Layout>
        <Image
          src={LightBulb}
          alt="Light Bulb"
          className="absolute right-8 bottom-4 m-0 self-end"
          height="160"
        />
        {/* <HireMe /> */}
      </main>
    </>
  );
}
